name: Code Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/code.yml"

env:
  GO_VERSION: "1.20.4"

jobs:

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Checkout Source Code
        uses: actions/checkout@v3
      # https://github.com/reviewdog/reviewdog/issues/1158
      # Permissions need to match container user
      - name: "Give Permissions"
        run: |
          sudo chown -R root $GITHUB_WORKSPACE
      - name: Spelling Check
        uses: reviewdog/action-misspell@v1.12.3
      - name: Revive Action
        uses: morphy2k/revive-action@v2
      - name: "Restore Permissions"
        run: |
          sudo chown -R $(id -u) $GITHUB_WORKSPACE
      - name: Check formatting
        run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)
